user_homepage:
    path:     /hello/{name}
    defaults: { _controller: UserBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: UserBundle:Registration:register }


